services:
  rabbitmq-mensageria:
    build: .
    container_name: rabbitmq-mensageria
    environment:
      RABBIT_DEFINITIONS: rabbit_definitions.json
    ports:
      - "15672:15672"
      - "5672:5672"
