name: Actions

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest

    outputs:
      changed_dirs: ${{ steps.detect.outputs.changed_dirs }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect Changed Directories
        id: detect
        run: |
          echo "Detectando serviços alterados..."
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "⚠️ Apenas um commit encontrado. Listando todos os arquivos..."
            CHANGED_DIRS=$(git ls-files | cut -d'/' -f1 | sort | uniq)
          else
            echo "Comparando últimas revisões..."
            CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD | cut -d'/' -f1 | sort | uniq)
          fi
          echo "Diretórios alterados: $CHANGED_DIRS"
          CHANGED_DIRS_CSV=$(echo "$CHANGED_DIRS" | paste -sd "," -)
          echo "Diretórios alterados (CSV): $CHANGED_DIRS_CSV"
          echo "changed_dirs=$CHANGED_DIRS_CSV" >> $GITHUB_OUTPUT

  compile-consulta:
    name: Compile Consulta
    runs-on: ubuntu-latest
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changed_dirs, 'consulta')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile
        run: |
          cd ./consulta
          mvn clean package -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: consulta-jar-file-${{ env.PROJECT_VERSION }}
          path: target/consulta-jar-file-${{ env.PROJECT_VERSION }}.jar

  compile-saque:
    name: Compile Saque
    runs-on: ubuntu-latest
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changed_dirs, 'saque')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile
        run: |
          cd ./saque
          mvn clean package -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: saque-jar-file-${{ env.PROJECT_VERSION }}
          path: target/saque-jar-file-${{ env.PROJECT_VERSION }}.jar

  compile-gateway:
    name: Compile Gateway
    runs-on: ubuntu-latest
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changed_dirs, 'gateway')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile
        run: |
          cd ./gateway
          mvn clean package -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gateway-jar-file-${{ env.PROJECT_VERSION }}
          path: target/gateway-jar-file-${{ env.PROJECT_VERSION }}.jar

  build-and-push-consulta:
    name: Build and Push Consulta
    runs-on: ubuntu-latest
    needs: compile-consulta

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: consulta-jar-file-${{ env.PROJECT_VERSION }}
          path: target

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        run: |
          cd ./consulta
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/sistema-microsservicos-financeiro-demo/consulta:$VERSION .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sistema-microsservicos-financeiro-demo/consulta:$VERSION

  build-and-push-saque:
    name: Build and Push Saque
    runs-on: ubuntu-latest
    needs: compile-saque

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: saque-jar-file-${{ env.PROJECT_VERSION }}
          path: target

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        run: |
          cd ./saque
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/sistema-microsservicos-financeiro-demo/saque:$VERSION .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sistema-microsservicos-financeiro-demo/saque:$VERSION

  build-and-push-gateway:
    name: Build and Push Gateway
    runs-on: ubuntu-latest
    needs: compile-gateway

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: gateway-jar-file-${{ env.PROJECT_VERSION }}
          path: target

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        run: |
          cd ./gateway
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/sistema-microsservicos-financeiro-demo/gateway:$VERSION .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sistema-microsservicos-financeiro-demo/gateway:$VERSION

  build-and-push-redis:
    name: Build and Push Redis
    runs-on: ubuntu-latest
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changed_dirs, 'redis')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        run: |
          cd ./redis
          VERSION=$(cat version || echo "latest")
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/sistema-microsservicos-financeiro-demo/redis:$VERSION .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sistema-microsservicos-financeiro-demo/redis:$VERSION

  build-and-push-rabbitmq:
    name: Build and Push RabbitMQ
    runs-on: ubuntu-latest
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changed_dirs, 'rabbitmq')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        run: |
          cd ./rabbitmq
          VERSION=$(cat version || echo "latest")
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/sistema-microsservicos-financeiro-demo/rabbitmq:$VERSION .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sistema-microsservicos-financeiro-demo/rabbitmq:$VERSION