name: Actions

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest

    outputs:
      changed_dirs: ${{ steps.detect.outputs.changed_dirs }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect Changed Directories
        id: detect
        run: |
          echo "Detectando serviços alterados..."
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "Apenas um commit encontrado. Listando todos os arquivos..."
            CHANGED_DIRS=$(git ls-files | cut -d'/' -f1 | sort | uniq)
          else
            echo "Comparando últimas revisões..."
            CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD | cut -d'/' -f1 | sort | uniq)
          fi
          echo "Diretórios alterados: $CHANGED_DIRS"
          CHANGED_DIRS_CONCAT=$(echo "$CHANGED_DIRS" | paste -sd "," -)
          echo "Diretórios alterados (CSV): $CHANGED_DIRS_CONCAT"
          echo "changed_dirs=$CHANGED_DIRS_CONCAT" >> $GITHUB_OUTPUT

  compile-consulta:
    name: Compile Consulta
    runs-on: ubuntu-latest
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changed_dirs, 'consulta')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile
        run: |
          cd ./consulta
          mvn clean package -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: consulta-jar-file
          path: ./consulta/target/*.jar

  compile-saque:
    name: Compile Saque
    runs-on: ubuntu-latest
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changed_dirs, 'saque')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile
        run: |
          cd ./saque
          mvn clean package -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: saque-jar-file
          path: ./saque/target/*.jar

  compile-gateway:
    name: Compile Gateway
    runs-on: ubuntu-latest
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changed_dirs, 'gateway')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile
        run: |
          cd ./gateway
          mvn clean package -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gateway-jar-file
          path: ./gateway/target/*.jar

  build-and-push-consulta:
    name: Build and Push Consulta
    runs-on: ubuntu-latest
    needs: compile-consulta

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: consulta-jar-file
          path: ./consulta/target

      - name: Set VERSION
        id: version
        run: |
          cd ./consulta
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version_test=$VERSION" >> $GITHUB_OUTPUT
          echo $VERSION

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./consulta
          push: true
          file: ./consulta/Dockerfile
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/microsservicos-financeiro-demo:consulta-${{ env.VERSION }}

  build-and-push-saque:
    name: Build and Push Saque
    runs-on: ubuntu-latest
    needs: compile-saque

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: saque-jar-file
          path: ./saque/target

      - name: Set VERSION
        id: version
        run: |
          cd ./saque
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./saque
          push: true
          file: ./saque/Dockerfile
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/microsservicos-financeiro-demo:saque-${{ env.VERSION }}

  build-and-push-gateway:
    name: Build and Push Gateway
    runs-on: ubuntu-latest
    needs: compile-gateway

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: gateway-jar-file
          path: ./gateway/target

      - name: Set VERSION
        id: version
        run: |
          cd ./gateway
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./gateway
          push: true
          file: ./gateway/Dockerfile
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/microsservicos-financeiro-demo:gateway-${{ env.VERSION }}

  build-and-push-redis:
    name: Build and Push Redis
    runs-on: ubuntu-latest
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changed_dirs, 'redis')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set VERSION
        id: version
        run: |
          cd ./redis
          VERSION=$(cat version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./redis
          push: true
          file: ./redis/Dockerfile
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/microsservicos-financeiro-demo:redis-${{ env.VERSION }}

  build-and-push-rabbitmq:
    name: Build and Push RabbitMQ
    runs-on: ubuntu-latest
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changed_dirs, 'rabbitmq')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set VERSION
        id: version
        run: |
          cd ./rabbitmq
          VERSION=$(cat version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./rabbitmq
          push: true
          file: ./rabbitmq/Dockerfile
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/microsservicos-financeiro-demo:rabbitmq-${{ env.VERSION }}

  update-env-repository:
    name: Update Environment Repository
    runs-on: ubuntu-latest
    needs:
      - detect-changes
      - build-and-push-consulta
      - build-and-push-saque
      - build-and-push-gateway
      - build-and-push-redis
      - build-and-push-rabbitmq

    steps:
      - name: Clone Env Repository
        run: |
          git clone https://github.com/tuliocesarfeldmann/swarm-devops-tgsi.git

      - name: Update docker-compose.yml
        run: |
          cd ./swarm-devops-tgsi/devops-tgsi-swarm
          echo ${{ needs.build-and-push-consulta.outputs.version }}
          echo ${{ needs.build-and-push-consulta.outputs.version_test }}
          if [[ "${{ needs.detect-changes.outputs.changed_dirs }}" == *"consulta"* ]]; then
            echo "Atualizando imagem do consulta para ${{ needs.build-and-push-consulta.outputs.version }}..."
            sed -i "s|image: .*consulta-.*|image: tulioufsm/microsservicos-financeiro-demo:consulta-${{ needs.build-and-push-consulta.outputs.version }}|g" docker-compose.yml
          fi

          if [[ "${{ needs.detect-changes.outputs.changed_dirs }}" == *"saque"* ]]; then
            echo "Atualizando imagem do saque para ${{ needs.build-and-push-saque.outputs.version }}..."
            sed -i "s|image: .*saque-.*|image: tulioufsm/microsservicos-financeiro-demo:saque-${{ needs.build-and-push-saque.outputs.version }}|g" docker-compose.yml
          fi

          if [[ "${{ needs.detect-changes.outputs.changed_dirs }}" == *"gateway"* ]]; then
            echo "Atualizando imagem do gateway para ${{ needs.build-and-push-gateway.outputs.version }}..."
            sed -i "s|image: .*gateway-.*|image: tulioufsm/microsservicos-financeiro-demo:gateway-${{ needs.build-and-push-gateway.outputs.version }}|g" docker-compose.yml
          fi

          # Redis e RabbitMQ
          if [[ "${{ needs.detect-changes.outputs.changed_dirs }}" == *"redis"* ]]; then
            echo "Atualizando imagem do redis para ${{ needs.build-and-push-redis.outputs.version }}..."
            sed -i "s|image: .*redis-.*|image: tulioufsm/microsservicos-financeiro-demo:redis-${{ needs.build-and-push-redis.outputs.version }}|g" docker-compose.yml
          fi

          if [[ "${{ needs.detect-changes.outputs.changed_dirs }}" == *"rabbitmq"* ]]; then
            echo "Atualizando imagem do rabbitmq para ${{ needs.build-and-push-rabbitmq.outputs.version }}..."
            sed -i "s|image: .*rabbitmq-.*|image: tulioufsm/microsservicos-financeiro-demo:rabbitmq-${{ needs.build-and-push-rabbitmq.outputs.version }}|g" docker-compose.yml
          fi

      - name: Commit and Push Changes
        run: |
          cd ./swarm-devops-tgsi
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Atualização automática do docker-compose.yml"
          git push https://${{ secrets.TOKEN_GITHUB }}@github.com/tuliocesarfeldmann/swarm-devops-tgsi.git

